-- Seed data for ASV Natz Penalty Tracker

-- Insert players
INSERT OR IGNORE INTO players (name) VALUES
('Maximilian Hofer'),
('Hannes Peintner'),
('Alex Braunhofer'),
('Alex Schraffel'),
('Andreas Fusco'),
('Armin Feretti'),
('Hannes Larcher'),
('Julian Brunner'),
('Leo Tauber'),
('Lukas Mayr'),
('Manuel Troger'),
('Martin Gasser'),
('Matthias Schmid'),
('Maximilian Schraffl'),
('Michael Mitterrutzner'),
('Michael Peintner'),
('Patrick Auer'),
('Patrick Pietersteiner'),
('Stefan Filo'),
('Stefan Peintner'),
('Manuel Auer'),
('Mauro Monti'),
('Tobias'),
('Jakob Unterholzner'),
('Fabian Bacher'),
('Emil Gabrieli'),
('Mardochee'),
('Oleg Schleiermann');

-- Insert penalty types
INSERT OR IGNORE INTO penalty_types (name, amount, description) VALUES
('Unentschuldigtes Fehlen im Trainingslager', 50.00, ''),
('Bier bei Essen Trainingslager', 10.00, ''),
('Busfahrer pflanzen', 5.00, ''),
('Alpha Aktion', 5.00, ''),
('Ball in Q5', 2.00, ''),
('Socken ohschneiden', 20.00, ''),
('Valentinstog fahln', 50.00, ''),
('Abschlussmatch verloren', 2.00, ''),
('Fehlen beim Spiel wegen Urlaub', 30.00, ''),
('Abwesenheit Urlaub während Meisterschaft', 10.00, ''),
('Unentschuldigtes Fehlen Spiel', 50.00, ''),
('Unentschieden Meisterschaftsspiel', 1.00, ''),
('Niederlage Meisterschaftsspiel', 2.00, ''),
('Spiel Socken ohschneiden', 20.00, ''),
('Elfer verursachen', 10.00, ''),
('Unentschuldigtes Fehlen beim Training', 20.00, ''),
('100%ige Chance liegen lossen', 5.00, ''),
('Falscher Einwurf', 5.00, ''),
('Elfer verschiaßn', 10.00, ''),
('Tormonn Papelle kregn', 5.00, ''),
('Freitig glei nochn Training gian', 2.00, ''),
('Schuache in Kabine ohklopfn', 5.00, ''),
('Kistenplan net einholten /pro Kopf', 30.00, ''),
('Übung bei training vertschecken', 1.00, ''),
('Torello 20 Pässe', 2.00, ''),
('Übern tennisplotz mit FB schuach gian', 5.00, ''),
('Nochn training gian ohne eps zu verraumen', 5.00, ''),
('Gelbsperre/Rotsperre pro Spiel', 15.00, ''),
('Kabinendienst vernachlässigt', 10.00, ''),
('Freitags Abschluss-Spiel verloren', 2.00, ''),
('Abwesenheit Urlaub in Vorbereitung', 5.00, ''),
('Glei nochn Hoamspiel gian(min 30 min.)', 10.00, ''),
('Saufn vorn Spiel', 50.00, ''),
('Unsportliches Verhalten gegenüber Mitspieler/Trai', 50.00, ''),
('Erstes Tor/Startelfeinsatz', 0.00, 'Kasten (ansonsten 20€)'),
('Eigentor', 0.00, 'Kasten (ansonsten 20€)'),
('Foto in Zeitung/Online', 2.00, ''),
('Sachen in Kabine/Platz vergessen', 5.00, ''),
('Unentschuldigtes fehlen beim Training ohne Absage', 15.00, ''),
('Rauchen im Trikot', 15.00, ''),
('Bei Spiel folscher Trainer', 20.00, ''),
('Folsches Trainingsgewond', 5.00, ''),
('Handy leitn in do kabine', 5.00, ''),
('Schiffn in do Dusche', 20.00, ''),
('Oan setzn in do Kabine (wenns stinkt 20€)', 5.00, ''),
('Frau/freindin fa an Mitspieler verraumen', 500.00, ''),
('Geburtstogsessen net innerholb 1 Monat gebrocht', 150.00, ''),
('Rote Karte wegn Unsportlichkeit', 50.00, ''),
('Gelbe Karte wegn Unsportlichkeit', 20.00, ''),
('Zu spät - Pauschale', 5.00, '');